### PR TITLE
Extract profile

### PR DESCRIPTION
**Pull request by kenkehoe**
This is to implement the Pull out profiles of PPI data over a specific location IDL code from #14 .

### CODE REVIEW

**Comment by kenkehoe** [comment]
@AdamTheisen the IDL program only uses azimuth and range to determine where to extract the profile from the PPI. Should we also set it up to extract over a lat/lon position?

**Comment by AdamTheisen** [comment]
@kenkehoe that would be useful. Using range probably distorts the profile. There might be something in pyart that we should look at. QVP

**Comment by AdamTheisen** [comment]
This would require us to convert to pyart radar object though and then convert back to xarray, however once PyART converts to xarray this would be more straight forward.  THoughts?

https://arm-doe.github.io/pyart/_modules/pyart/retrieve/qvp.html

**Comment by kenkehoe** [comment]
Interesting. I will need to check out PyART more. I am not following the code. 

The PR code does take the change in range with increasing angle so the profile should be pretty straight. Maybe add in the PyART option but also keep this code?

**Comment by AdamTheisen** [comment]
@kenkehoe sounds like a plan.  I can go ahead and merge.  The only question I have is on the inclusion of the following in the test code.  I do not think this is necessary for pytest

**if __name__ == '__main__':
    test_cloud_mask()
    test_calc_avg_profile()
    test_extract_profile()**

**Comment by kenkehoe** [comment]
OK I'll take that code out. Don't merge until I have the lat/lon profile extraction included too. I'll let you know when.

**Comment by kenkehoe** [comment]
After looking at what was needed, I decided to just add a function to calculate the range and azimuth between two lat/lon pairs instead of importing PyART to extract profile. Also, found an issue in calculating distance.

**Comment by AdamTheisen** [comment]
@kenkehoe tests pass and the code looks good.  Are you ready to merge this in?

**Comment by kenkehoe** [comment]
Yeah I believe it is good to go.

**Pull request merged**
